// D&D conversions approved for the 28 planar two-piece bonuses.
export const ADAPTATIONS={
  301:{bonuses:[['str',1]],text:'Strength +1; +1 more at 35 ft speed.'},
  302:{bonuses:[['con',1]],text:'Constitution +1; at 35 ft speed allies gain Strength +1.'},
  303:{bonuses:[['effectHit',1]],text:'Effect Hit Rate +1 and Strength +1.',extra:[['str',1]]},
  304:{bonuses:[['dex',1]],text:'Dexterity +1; another +1 with Effect Hit Rate +2.'},
  305:{bonuses:[['critDamageBonus',1]],text:'Critical damage bonus +1; conditional first attack gains Crit Range +3.'},
  306:{bonuses:[['critRange',1]],text:'Crit Range +1; Ultimate and follow-up damage +1 when eligible.'},
  307:{bonuses:[['breakEffect',1]],text:'Break Effect +1; another +1 at 45 ft speed.'},
  308:{bonuses:[['energyRegen',1]],text:'Energy Regen +1; advance on entering combat at 35 ft speed.'},
  309:{bonuses:[['critRange',1]],text:'Crit Range +1; basic attack and Skill damage +1 when eligible.'},
  310:{bonuses:[['savingThrow',1]],text:'Saving throw +1; allies gain critical damage bonus +1 when eligible.'},
  311:{bonuses:[['str',1]],text:'Strength +1; +1 damage at 40 ft speed, +2 at 50 ft.'},
  312:{bonuses:[['energyRegen',1]],text:'Energy Regen +1; matching-element allies gain +1 damage.'},
  313:{bonuses:[['critRange',1]],text:'Crit Range +1; enemy defeat grants critical damage bonus +1, then +2 after the second, for three turns.'},
  314:{bonuses:[['str',1]],text:'Strength +1; Crit Range +1 with a same-Path party member.'},
  315:{bonuses:[],text:'Allied follow-up attacks build five Merit stacks: +1 follow-up damage, plus critical damage bonus +1 at five.'},
  316:{bonuses:[['speed',5]],text:'Speed +5 ft; Fire-weak hit grants Break Effect +2 for one turn.'},
  317:{bonuses:[['energyRegen',1]],text:'Energy Regen +1; selected recipient gains nonstacking Strength +1.'},
  318:{bonuses:[['critDamageBonus',1]],text:'Critical damage bonus +1, plus two more while a summon is on the field.'},
  319:{bonuses:[['con',1]],text:'Constitution +1; at 60 or greater maximum HP, wearer and memosprite gain critical damage bonus +1.'},
  320:{bonuses:[['speed',5]],text:'Speed +5 ft; at 40 ft healing +1, at 55 ft healing +2.'},
  321:{bonuses:[],text:'For each ally above or below four, wearer and memosprite gain +1 damage (caps +4 or +3).'},
  322:{bonuses:[['str',1]],text:'Strength +1; at 18 Strength DoT +1, at 22 Strength DoT +2.'},
  323:{bonuses:[['critRange',1]],text:'Crit Range +1; summoned memosprite grants allies nonstacking Speed +5 ft.'},
  324:{bonuses:[['critDamageBonus',1]],text:'Critical damage bonus +1; spending three Skill Points grants two more for three turns.'},
  325:{bonuses:[['elation',1]],text:'Elation damage +1; at Punchline 4/8 gain critical damage bonus +1/+2.'},
  326:{bonuses:[],text:'Follow-up attack grants Strength +1 for two turns; enemy defeat grants allies critical damage bonus +1.'},
  327:{bonuses:[['critRange',1]],text:'Crit Range +1; with another Trailblaze Companion gain critical damage bonus +2.'},
  328:{bonuses:[],text:'At maximum Energy 41–58 gain +1 damage, at 59–60 gain +2.'},
  329:{bonuses:[['speed',5]],text:'Speed +5 ft; at 45 ft or higher, allies in combat gain nonstacking Break Effect +1.'},
  330:{bonuses:[['speed',5]],text:'Speed +5 ft; on the wearer’s first turn of combat, Punchline becomes 4 and the wearer immediately gains an Action Advance turn.'}
};
